### ISSUE TITLE
Create dependencies for groups and services

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#40]
Before running a service with `depends-on`, it checks all the dependencies healthcheck, and just when all the dependencies are healthy it will run the main service.

NOTE: it is necessary to check if this is already necessary, or if it can be easily defined with docker compose.

example:

```yaml
version: 1.0.0
compose-app: docker-compose
service-groups:
  - name: group1
    project-name: project1  # optional
    compose-path: containers/tests/group1/compose.yaml
    env-file: .env
    services:
      default: service1-1,service1-3
      list:
        - name: service1-1
          depends-on:
            - dep1
        - name: service1-2
        - name: service1-3
    dependencies:
      - name: dep1
        source:
          # local:
          #   wdir: /tmp
          #   path: containers/.containers-sugar.yaml
          # or
          # repo:
          #   url: https://github.com/alertadengue/copernicus
          #   path: .containers-sugar.yaml
          #   branch: ...
          #   commit: ...
        env-file: .env
        services:
          - group1.service-dep1.1
          - group2.service-dep1.2

  - name: group2
    project-name: null  # optional
    compose-path: containers/tests/group2/compose.yaml
    env-file: .env
    services:
      default: null
      list:
        - name: service2-1
        - name: service2-2

  - name: group-mix
    project-name: null  # optional
    compose-path:
      - containers/tests/group1/compose.yaml
      - containers/tests/group2/compose.yaml
    env-file: .env
    services:
      default: null
      list:
        - name: service1-1
        - name: service1-2
        - name: service2-1
        - name: service2-2
```
