### ISSUE TITLE
Change service groups items from list to dict 

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#43]
Currently, all the groups are inside a list, it is necessary to change from list to dictionary.

Current state:

```yaml
version: 1.0
compose-app: docker compose
env-file: ./src/.env
defaults:
  group: dev
  project-name: rinchen

groups:
  - name: dev
    compose-path: containers/docker-compose.yaml
    services:
      default: web
      available:
        - name: web
```

Desired:

```yaml
version: 1.0
compose-app: docker compose
env-file: ./src/.env
defaults:
  group: dev
  project-name: rinchen

groups:
  dev:
    compose-path: containers/docker-compose.yaml
    services:
      default: web
      available:
        - name: web
```

PS: this is similar to what we already  have in makim (https://github.com/osl-incubator/makim/blob/main/makim/makim.py#L152)
PS2: we don't need to keep support for a default group called `default`.
