### ISSUE TITLE
SPEC: Add a new key in the root of the config file for services

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#61]
Add a new key in the root of the config file for services. Example:

```
version: 1.0.0
compose-app: docker-compose
env-file: .env
services:
  default: service1,service3
  list:
    - name: service1
      health-check: true
    - name: service2
      health-check: false
    - name: service3
      health-check: true
```

when the services item is given, `groups` should not be given, otherwise it should raise an error.
