### ISSUE TITLE
add support for multiples env files

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/sugar#88]
Currently, the env-file attribute just accepts a string, which means that it accepts just one file. 
it would be nice to have support for a string (when just one file is required) or a list (when multiple files are required)

for example:

```yaml

backend: compose
env-file: .env
defaults:
  profile: "${{ env.SUGAR_PROFILE }}"
  project-name: "sugar-${{ env.SUGAR_PROJECT_NAME }}"
profiles:
  profile1:
    project-name: project1
    config-path: tests/containers/profile1/compose.yaml
    env-file: .env
    services:
      default: service1-1,service1-3
      available:
        - name: service1-1
        - name: service1-2
        - name: service1-3

  profile2:
    config-path: tests/containers/profile2/compose.yaml
    env-file: .env
    services:
      available:
        - name: service2-1
        - name: service2-2

```

using multiple files:

```yaml

backend: compose
env-file: 
  - .env
  - .env2
defaults:
  profile: "${{ env.SUGAR_PROFILE }}"
  project-name: "sugar-${{ env.SUGAR_PROJECT_NAME }}"
profiles:
  profile1:
    project-name: project1
    config-path: tests/containers/profile1/compose.yaml
    env-file: 
      - .env
      - .env2
    services:
      default: service1-1,service1-3
      available:
        - name: service1-1
        - name: service1-2
        - name: service1-

```

ref: https://github.com/osl-incubator/sugar/blob/main/.sugar.yaml#L2
